// <auto-generated />
using MVCDataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCDataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220708191813_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCDataAccess.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rafiganj",
                            Name = "Zafer Eqbal"
                        },
                        new
                        {
                            Id = 2,
                            Address = "NewArea",
                            Name = "Taukir Alam"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Basariya",
                            Name = "Arbaaz Khan"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rajabagicha",
                            Name = "Harsh Babu"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Duniya Mohalla",
                            Name = "Ravish Kumar"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Daudnagar",
                            Name = "Yasin Ekbal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
